### ISSUE TITLE
Wrong IP when multiple networks in Docker

### ISSUE THREAD

**Issue by Pawamoy** [jazzband/django-debug-toolbar#1054]
The solution used in [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) does not work when the Django container is connected to multiple networks in Docker. The solution is something like the following (taken from this [SO post](https://stackoverflow.com/questions/26898597/django-debug-toolbar-and-docker/45624773)): 

```python
import socket

ip = socket.gethostbyname(socket.gethostname())
INTERNAL_IPS = ['127.0.0.1', ip[:-1] + '1']
```

My Docker Compose configuration has the following items:

```yaml
networks:
  web_network: {}
  cache_network: {}
  database_network: {}


services:
  djangoapp:
    networks:
      - database_network
      - web_network
      - cache_network
```

Now the IP returned by `ip = socket.gethostbyname(socket.gethostname())` is not always the same. It seems to be the IP of one of the different available networks (if that makes sense). So sometimes it works, but most of the time it does not. 

I ended up adding all the possible IPs based on the one returned by `socket`, something like:
```python
def internal_docker_ips(base_ip):
    numbers = base_ip.split('.')
    return [
        '.'.join([numbers[0], str(i), numbers[2], str(j)])
        for i in range(1, 254) for j in (1, 3)  # all IPs ending with '.1' and '.3'
    ]

INTERNAL_IPS = [
    '127.0.0.1',
]

INTERNAL_IPS.extend(
    internal_docker_ips(
        socket.gethostbyname(
            socket.gethostname())))

# ['127.0.0.1', '172.1.0.1', '172.1.0.3', '172.2.0.1', '172.2.0.3', ..., '172.253.0.1', '172.253.0.3']
```

Is there a cleaner workaround for this? Did any of you have the same issue? It might not be related to Django Debug Toolbar itself but any help is appreciated and will I believe be useful for others.
