### ISSUE TITLE
Close button styling in 3.0a2

### ISSUE THREAD

**Issue by OutOfFocus4** [jazzband/django-debug-toolbar#1311]
I am using version 3.0a2, and I noticed that the close button styling is broken when viewing the SQL panel.

In addition to the normal "×", there is a circle, and that circle changes color when hovered over.

![Close circle](https://user-images.githubusercontent.com/50265209/92242097-498d0700-ee8d-11ea-9e46-9a5b86555aab.png)

This issue can be fixed by removing the following CSS rules from `toolbar.css`:

```css
/* line 302: */#djDebug .djdt-panelContent .djDebugClose {
...
    border: 6px solid #ddd;/* Remove this */
    border-radius: 50%;/* and this */
    background: #fff;/* and this */
...
}
```

In addition, the `.djDebugClose:hover` CSS rule on line 321 should change the `color` rather than the `background`.
