### ISSUE TITLE
Bug Report: Debug Toolbar Doesn't Respond or Not Visible

### ISSUE THREAD

**Issue by WayneLambert** [jazzband/django-debug-toolbar#1342]
**Expected Behaviour**

Following an update to version 3.1.1, when clicking on the links within the toolbar, it should bring up the relevant debug info for the respective panel.

**Actual Behaviour**

When clicking any of the panels, it does not respond in any way. It is visible in my normal development browser of Firefox.

When I check this using Opera (which I have intentionially set without any extensions and to completely clear the cache and all cookies on a fresh startup), it is not visible at all. I have also tested on Chrome and Safari and it isn't visible there neither.

I considered that it might be a third party panel `TemplateProfilerPanel` that I have installed which might be in conflict and not yet compatible, however I uninstalled the panel and removed its configuration and it still doesn't work.

My configuration setup is installing using Pipenv as the package manager within a web container using Docker compose.

It used to work with no issues using version 2.2. I have now reverted back to version 2.2 which I can happily use again even with the third party panel installed and configured.

When upgrading, I retained the previously working configuration (with version 2.2) within my settings, urls, etc. If you'd like to reference the GitHub repo, it can be found at [https://github.com/WayneLambert/portfolio](https://github.com/WayneLambert/portfolio)

For reference/convenience, this was my pinned Pipfile as at the time of the bug report:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
django-debug-toolbar = "==3.1.1"
django-extensions = "==3.0.9"
pytest = "==6.0.2"
coverage = "==5.3"
pytest-django = "==3.10.0"
pytest-cov = "==2.10.1"
pytest-pythonpath = "==0.7.3"
pytest-factoryboy = "==2.0.3"
mixer = "==6.1.3"
hypothesis = "==5.35.4"
django-coverage-plugin = "==1.8.0"
autopep8 = "==1.5.4"
ptvsd = "==4.3.2"
dj-database-url = "==0.5.0"
bandit = "==1.6.2"
interrogate = "==1.3.1"
wily = "==1.19.0"
bpython = "==0.19"
pylint = "==2.6.0"
pylint-django = "==2.3.0"
pycodestyle = "==2.6.0"
ipdb = "==0.13.3"
ipython = "==7.18.1"
rich = "==7.0.0"
pytest-randomly = "==3.4.1"
pytest-vcr = "==1.0.2"
pdbpp = "==0.10.2"
pytest-mock = "==3.3.1"
pytest-xdist = "==2.1.0"

[packages]
django = "==3.1.1"
djangorestframework = "==3.11.1"
django-crispy-forms = "==1.9.2"
django-recaptcha = "==2.0.6"
django-widget-tweaks = "==1.4.8"
django-shapeshifter = "==18.9.23"
django-bootstrap4 = "==2.2.0"
django-guardian = "==2.3.0"
django-storages = "==1.10.1"
django-ses = "==1.0.3"
django-filter = "==2.3.0"
dj-database-url = "==0.5.0"
psycopg2-binary = "==2.8.6"
gunicorn = "==20.0.4"
whitenoise = "==5.2.0"
requests = "==2.24.0"
beautifulsoup4 = "==4.9.1"
markdown = "==3.2.2"
boto3 = "==1.15.1"
pygments = "==2.6.1"
pillow = "==7.2.0"
django-tinymce = "==3.0.2"
django-redis = "==4.12.1"
bleach = "==3.2.1"

[requires]
python_version = "3.8"
```

Thank you!
